POST http://localhost:3000/api/v1/auth/register
###
POST http://localhost:3000/api/v1/auth/login
###
POST http://localhost:3000/api/v1/auth/logout
###
GET http://localhost:3000/api/v1/users/1
###
PUT http://localhost:3000/api/v1/users/1
###
DELETE http://localhost:3000/api/v1/users/1
###
GET http://localhost:3000/api/v1/items/1
###
POST http://localhost:3000/api/v1/items/list_item